# permissions for end users to view trainings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: training-viewer-role
rules:
- apiGroups:
  - training.tektutor.org
  resources:
  - trainings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - training.tektutor.org
  resources:
  - trainings/status
  verbs:
  - get
